### ISSUE TITLE
function names in ViewController doesn't change

### ISSUE THREAD

**Issue by qliuaq** [Elliotsomething/ConfuseCode#1]
Hi, this code is helpful for me! I ran this code in Xcode but I found that the "sample", "seg1", "seg2" didn't change in ViewController though they changed in codeObfuscation.m. Does this right in that way? I'm a little confused. Can you help me out? Thanks so much!

**Comment by Elliotsomething** [comment]
Are sure that the  "sample", "seg1", "seg2" add to func.plist?or that if the confuse.sh is running?
